#!/bin/bash
sleep 1;
conky -c ~/.conky/.conkyrc_first -x 3280 -y 1042 &
conky -c ~/.conky/.conkyrc_left -x 1366 -y 1042 &
#conky -c ~/.conky/.conkyrc_mid

#sudo apt install lm-sensors hddtemp lunar
#sudo chmod u+s /sbin/hddtemp
#sudo ln -s /sbin/hddtemp /bin/hddtemp
